title: Testseite
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
remote_theme: "mmistakes/minimal-mistakes@4.14.1"
plugins: jekyll-include-cache
